const menuItems=[
 {name:'Chocolate Chip',cat:'classics',price:'$5',desc:'Brown butter dough, milk & dark chocolate, flaky salt.'},
 {name:'Cookies & Cream',cat:'classics',price:'$5',desc:'Vanilla cookie packed with chocolate sandwich cookie pieces.'},
 {name:'S’mores',cat:'stuffed',price:'$6',desc:'Graham cookie, chocolate chunks, gooey marshmallow center.'},
 {name:'Dubai Chocolate',cat:'stuffed',price:'$7',desc:'Chocolate cookie, pistachio cream and crispy kataifi.'},
 {name:'Ramadan Box',cat:'seasonal',price:'$32',desc:'[EDITABLE] A festive six-cookie assortment for sharing.'},
 {name:'The Love Box',cat:'boxes',price:'$28',desc:'[EDITABLE] Six signature cookies dressed for gifting.'}
];
const reviews=[
 {quote:'“The perfect balance of crispy edges and that warm, gooey center. We finished the box before we even made it home.”',name:'Aisha R.',meta:'DFW cookie lover'},
 {quote:'“Beautifully packaged, incredibly fresh, and every flavor felt special. They were the first thing gone at our event!”',name:'Sara M.',meta:'Custom event order'},
 {quote:'“You can taste the care in every bite. The s’mores cookie might genuinely be the best cookie I’ve ever had.”',name:'Noor K.',meta:'Repeat customer'}
];
const hours={0:null,1:['10:00','18:00'],2:['10:00','18:00'],3:['10:00','18:00'],4:['10:00','18:00'],5:['10:00','19:00'],6:['11:00','16:00']};
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

const menuGrid=document.querySelector('#menu-grid');
menuGrid.innerHTML=menuItems.map((item,i)=>`<article class="menu-card" data-category="${item.cat}" style="animation-delay:${i*.05}s"><div class="menu-image"><img src="assets/images/${String(i+1).padStart(2,'0')}.webp" alt="${item.name} cookie" loading="lazy" decoding="async"></div><div class="menu-info"><span class="tag">${item.cat}</span><div><h3>${item.name}</h3><strong>${item.price}</strong></div><p>${item.desc}</p></div></article>`).join('');
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-selected','false')});btn.classList.add('active');btn.setAttribute('aria-selected','true');document.querySelectorAll('.menu-card').forEach((card,i)=>{const show=btn.dataset.filter==='all'||card.dataset.category===btn.dataset.filter;card.classList.toggle('hidden',!show);if(show){card.style.animation='none';requestAnimationFrame(()=>{card.style.animation=`cardIn .45s ${i*.04}s both`})}})}));

const track=document.querySelector('#testimonial-track'),dots=document.querySelector('#carousel-dots');let slide=0,slideTimer;
track.innerHTML=reviews.map(r=>`<article class="testimonial"><div class="stars">★★★★★</div><blockquote>${r.quote}</blockquote><p class="reviewer">${r.name} · <span>${r.meta} [EDITABLE]</span></p></article>`).join('');
dots.innerHTML=reviews.map((_,i)=>`<button aria-label="Go to review ${i+1}" class="${i===0?'active':''}"></button>`).join('');
function goToSlide(i){slide=(i+reviews.length)%reviews.length;track.style.transform=`translateX(-${slide*100}%)`;[...dots.children].forEach((d,n)=>d.classList.toggle('active',n===slide));clearInterval(slideTimer);slideTimer=setInterval(()=>goToSlide(slide+1),6000)}
document.querySelector('#prev-review').onclick=()=>goToSlide(slide-1);document.querySelector('#next-review').onclick=()=>goToSlide(slide+1);[...dots.children].forEach((d,i)=>d.onclick=()=>goToSlide(i));goToSlide(0);
let touchStart=0;track.addEventListener('touchstart',e=>touchStart=e.changedTouches[0].screenX,{passive:true});track.addEventListener('touchend',e=>{let d=e.changedTouches[0].screenX-touchStart;if(Math.abs(d)>40)goToSlide(slide+(d<0?1:-1))},{passive:true});

const header=document.querySelector('#site-header');const toggle=document.querySelector('.nav-toggle');const navLinks=document.querySelector('.nav-links');
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>35),{passive:true});toggle.onclick=()=>{const open=navLinks.classList.toggle('open');toggle.setAttribute('aria-expanded',open)};navLinks.querySelectorAll('a').forEach(a=>a.onclick=()=>{navLinks.classList.remove('open');toggle.setAttribute('aria-expanded','false')});
document.querySelectorAll('a[href^="#"]:not([href="#"])').forEach(link=>link.addEventListener('click',event=>{const target=document.querySelector(link.getAttribute('href'));if(!target)return;event.preventDefault();target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});history.replaceState(null,'',location.pathname+location.search)}));if(location.hash){const initialTarget=document.querySelector(location.hash);if(initialTarget){requestAnimationFrame(()=>{initialTarget.scrollIntoView({block:'start'});history.replaceState(null,'',location.pathname+location.search)})}}
const parallax=document.querySelector('[data-parallax]');window.addEventListener('scroll',()=>{if(innerWidth>720&&scrollY<innerHeight)parallax.style.transform=`translateY(${scrollY*.08}px)`},{passive:true});
const rotatingWord=document.querySelector('.rotating-word em');const heroWords=['sweeter.','warmer.','better.'];let wordIndex=0;if(!matchMedia('(prefers-reduced-motion: reduce)').matches){setInterval(()=>{rotatingWord.classList.add('word-out');setTimeout(()=>{wordIndex=(wordIndex+1)%heroWords.length;rotatingWord.textContent=heroWords[wordIndex];rotatingWord.classList.remove('word-out');rotatingWord.classList.add('word-in');setTimeout(()=>rotatingWord.classList.remove('word-in'),450)},280)},3200)}
const countUp=document.querySelector('.count-up');const countTarget=Number(countUp.dataset.count);let countStarted=false;function animateCount(){if(countStarted)return;countStarted=true;const started=performance.now(),duration=1400;function tick(now){const progress=Math.min((now-started)/duration,1);countUp.textContent=Math.round(countTarget*(1-Math.pow(1-progress,3)));if(progress<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}new IntersectionObserver(entries=>{if(entries[0].isIntersecting)animateCount()},{threshold:.5}).observe(countUp);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const storyCount=document.querySelector('[data-story-count]');let storyCounted=false;new IntersectionObserver(entries=>{if(!entries[0].isIntersecting||storyCounted)return;storyCounted=true;const start=performance.now();function tick(now){const p=Math.min((now-start)/1100,1);storyCount.textContent=Math.round(100*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)},{threshold:.7}).observe(storyCount);

const lightbox=document.querySelector('#lightbox');document.querySelectorAll('.gallery-item').forEach(item=>item.onclick=()=>{const image=lightbox.querySelector('img');image.src=item.dataset.image;image.alt=item.querySelector('img').alt;lightbox.querySelector('small').textContent=item.dataset.label;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';lightbox.querySelector('button').focus()});function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');document.body.style.overflow=''}lightbox.querySelector('.lightbox-close').onclick=closeLightbox;lightbox.onclick=e=>{if(e.target===lightbox)closeLightbox()};addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});

const orderForm=document.querySelector('#order-form');const validators={name:v=>v.trim().length>1?'':'Please enter your name.',email:v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)?'':'Enter a valid email address.',type:v=>v?'':'Please choose an order type.',date:v=>v?'':'Please choose your desired date.',message:v=>v.trim().length>=10?'':'Add at least 10 characters so we can help.'};
function validateField(field){const msg=validators[field.name]?.(field.value)||'';field.classList.toggle('invalid',!!msg);field.parentElement.querySelector('.error').textContent=msg;return !msg}orderForm.querySelectorAll('input,select,textarea').forEach(field=>{field.addEventListener('blur',()=>validateField(field));field.addEventListener('input',()=>{if(field.classList.contains('invalid'))validateField(field)})});orderForm.onsubmit=e=>{e.preventDefault();const fields=[...orderForm.querySelectorAll('input,select,textarea')];const valid=fields.map(validateField).every(Boolean);if(valid){orderForm.classList.add('success');orderForm.querySelector('.form-success').focus()}};document.querySelector('#reset-form').onclick=()=>{orderForm.reset();orderForm.classList.remove('success')};

const hoursList=document.querySelector('#hours-list');const now=new Date(),today=now.getDay();hoursList.innerHTML=dayNames.map((day,i)=>`<div class="${i===today?'today':''}"><span>${day}${i===today?' · Today':''}</span><span>${hours[i]?`${formatTime(hours[i][0])}–${formatTime(hours[i][1])}`:'Closed'}</span></div>`).join('');function formatTime(t){let[h,m]=t.split(':').map(Number);return`${h%12||12}${m?':'+String(m).padStart(2,'0'):''} ${h>=12?'PM':'AM'}`};const status=document.querySelector('#store-status');let open=false;if(hours[today]){const mins=now.getHours()*60+now.getMinutes();const [sh,sm]=hours[today][0].split(':').map(Number),[eh,em]=hours[today][1].split(':').map(Number);open=mins>=sh*60+sm&&mins<eh*60+em}status.classList.add(open?'open':'closed');status.querySelector('span').textContent=open?'Open now · accepting inquiries':'Closed now · inquiries still welcome';

document.querySelector('#newsletter-form').onsubmit=e=>{e.preventDefault();const input=e.currentTarget.querySelector('input');if(input.checkValidity()){document.querySelector('#newsletter-message').textContent='You’re on the sweet list! ✓';input.value=''}};document.querySelector('#year').textContent=new Date().getFullYear();
